#!/bin/bash

config=".config/alacritty/alacritty.toml"

declare -A updates
updates["background = \"0xDYECOLOR\" # dye enable"]="background"
updates["foreground = \"0xDYECOLOR\" # dye enable"]="foreground"

updates["blacka = \"0xDYECOLOR\" # dye normal"]="normal_black"
updates["red = \"0xDYECOLOR\" # dye normal"]="normal_red"
updates["green = \"0xDYECOLOR\" # dye normal"]="normal_green"
updates["yellow = \"0xDYECOLOR\" # dye normal"]="normal_yellow"
updates["blue=  \"0xDYECOLOR\" # dye normal"]="normal_blue"
updates["magenta = \"0xDYECOLOR\" # dye normal"]="normal_magenta"
updates["white = \"0xDYECOLOR\" # dye normal"]="normal_white"

updates["black = \"0xDYECOLOR\" # dye bright"]="bright_black"
updates["red = \"0xDYECOLOR\" # dye bright"]="bright_red"
updates["green = \"0xDYECOLOR\" # dye bright"]="bright_green"
updates["yellow = \"0xDYECOLOR\" # dye bright"]="bright_yellow"
updates["blue = \"0xDYECOLOR\" # dye bright"]="bright_blue"
updates["magenta = \"0xDYECOLOR\" # dye bright"]="bright_magenta"
updates["white = \"0xDYECOLOR\" # dye bright"]="bright_white"
