#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
#bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# manually added 20171008
bspc config window_gap              6
bspc config focused_border_color    "#8AB3B5"
#bspc config focused_border_color    "#6699cc"
#bspc config focused_border_color    "#1E90FF"

#bspc config top_padding             20 # enable for status bar
#i3status | dzen2 -fn "xft:Monospace:size=10" -bg "#222222" -ta r
#i3status | dzen2 -ta r # enable for status bar
