# [vim-like keybindings](https://github.com/LGUG2Z/helix-vim/blob/master/config.toml)

theme = "base16_terminal"

[editor]
auto-completion = false
auto-format = false
auto-pairs = false
bufferline = "always"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
#gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.lsp]
auto-signature-help = false

[editor.soft-wrap]
enable = true

#[editor.cursor-shape]
#insert = "bar"
#normal = "block"
#select = "underline"

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
# d = ["yank_main_selection_to_clipboard", "delete_selection"]
# y = "yank_main_selection_to_clipboard"
# p = "paste_clipboard_before"

#x = ["extend_line_below", "select_mode"]
#V = ["extend_line_below", "select_mode"]
#A-x = "extend_to_line_bounds"
#X = ["extend_line_up", "extend_to_line_bounds", "select_mode"]

space = {t = ":sh hxpicker"}

[keys.select]
# d = ["yank_main_selection_to_clipboard", "delete_selection"]
# y = "yank_main_selection_to_clipboard"

#A-x = "extend_to_line_bounds"
#X = ["extend_line_up", "extend_to_line_bounds"]
