# [vim-like keybindings](https://github.com/LGUG2Z/helix-vim/blob/master/config.toml)

theme = "base16_terminal"

[editor]
auto-pairs = false
# line-number = "none"
gutters = []
#gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.soft-wrap]
enable = true

#[editor.cursor-shape]
#insert = "bar"
#normal = "block"
#select = "underline"

[keys.normal]
#y = "yank_main_selection_to_clipboard"
#p = "paste_clipboard_before"

#x = ["extend_line_below", "select_mode"]
#V = ["extend_line_below", "select_mode"]
#A-x = "extend_to_line_bounds"
#X = ["extend_line_up", "extend_to_line_bounds", "select_mode"]

# vim-like keybindings
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]

x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]

w = ["move_next_word_start", "move_char_right", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]

i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

u = ["undo", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
#y = "yank_main_selection_to_clipboard"

#A-x = "extend_to_line_bounds"
#X = ["extend_line_up", "extend_to_line_bounds"]

# vim keybindings
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
